
DROP TABLE IF EXISTS `tm_config`;
CREATE TABLE `tm_config` (
  `CFG_CODE` varchar(64) NOT NULL COMMENT '配置编码',
  `CFG_NAME` varchar(64) NOT NULL COMMENT '配置名称',
  `CFG_VALUE` varchar(128) NOT NULL COMMENT '配置值',
  `P_CFG_CODE` varchar(64) DEFAULT NULL COMMENT '父配置编码',
  `SEQ_NO` int(11) NOT NULL COMMENT '排序',
  `DESCRIPTION` varchar(128) DEFAULT NULL COMMENT '配置描述',
  `REMARK` varchar(256) DEFAULT NULL COMMENT '备注',
  `EXT1` varchar(128) DEFAULT NULL,
  `EXT2` varchar(128) DEFAULT NULL,
  `EXT3` varchar(128) DEFAULT NULL,
  `EXT4` varchar(64) DEFAULT NULL,
  `EXT5` varchar(64) DEFAULT NULL,
  `R_CFG_CODE` varchar(64) DEFAULT NULL COMMENT '根配置编码',
  `CRT_USERID` varchar(40) DEFAULT NULL COMMENT '建立人ID',
  `CRT_USERNAME` varchar(32) DEFAULT NULL COMMENT '建立人姓名',
  `CRT_TIME` datetime DEFAULT NULL COMMENT '建立时间',
  `MD_USERID` varchar(40) DEFAULT NULL COMMENT '修改人ID',
  `MD_TIME` datetime DEFAULT NULL COMMENT '修改时间',
  `MD_USERNAME` varchar(32) DEFAULT NULL COMMENT '修改人姓名',
  PRIMARY KEY (`CFG_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='系统选项配置 TM_CONFIG';

DROP TABLE IF EXISTS `ts_dictionary`;
CREATE TABLE `ts_dictionary` (
  `DIC_ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '字典ID',
  `DIC_KEY` varchar(100) NOT NULL COMMENT 'KEY，英文数字下划线组成',
  `DIC_NAME` varchar(300) DEFAULT NULL COMMENT '名称，默认用于展示的文字',
  `DESCRIPT` varchar(1200) DEFAULT NULL COMMENT '描述文字',
  `PARENT_ID` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '父ID',
  `DIC_VALUE` varchar(1000) DEFAULT NULL COMMENT '值',
  `SN` int(10) DEFAULT NULL COMMENT '序号',
  `PKEY_PATH` varchar(500) NOT NULL COMMENT '如节点Key路径',
  `STATUS` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '状态：无效0，有效1',
  `CREATE_BY` varchar(30) DEFAULT NULL COMMENT '创建者用户账号',
  `CREATE_TM` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_BY` varchar(30) DEFAULT NULL COMMENT '更新者用户账号',
  `UPDATE_TM` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`DIC_ID`),
  FULLTEXT KEY `IDX_DICTIONARY` (`DIC_KEY`,`PKEY_PATH`)
) ENGINE=InnoDB AUTO_INCREMENT=2258 DEFAULT CHARSET=utf8 COMMENT='配置表';



