
DROP TABLE IF EXISTS `ts_dictionary`;
CREATE TABLE `ts_dictionary` (
  `DIC_ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '字典ID',
  `DIC_KEY` varchar(100) NOT NULL COMMENT 'KEY，英文数字下划线组成',
  `DIC_NAME` varchar(300) DEFAULT NULL COMMENT '名称，默认用于展示的文字',
  `DESCRIPT` varchar(1200) DEFAULT NULL COMMENT '描述文字',
  `PARENT_ID` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '父ID',
  `DIC_VALUE` varchar(1000) DEFAULT NULL COMMENT '值',
  `SN` int(10) DEFAULT NULL COMMENT '序号',
  `PKEY_PATH` varchar(500) NOT NULL COMMENT '如节点Key路径',
  `STATUS` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '状态：无效0，有效1',
  `CREATE_BY` varchar(30) DEFAULT NULL COMMENT '创建者用户账号',
  `CREATE_TM` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_BY` varchar(30) DEFAULT NULL COMMENT '更新者用户账号',
  `UPDATE_TM` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`DIC_ID`),
  FULLTEXT KEY `IDX_DICTIONARY` (`DIC_KEY`,`PKEY_PATH`)
) ENGINE=InnoDB AUTO_INCREMENT=2258 DEFAULT CHARSET=utf8 COMMENT='配置表';



